name: Checkout with Action
on: [push]

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -a
      - uses: actions/checkout@v6.0.2
      - name: List after
        run: ls -a


