name: Checkout with Action
on: [push]

jobs:
  checkout-action:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -a
      - uses: actions/checkout@v6.0.2
      - name: List after
        run: ls -a


  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -a
      - name: Checkout
        run: |
          git init
          git remote add origin "http://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
      - name: List after
        run: ls -a
    